module.exports={
    PRODUCT_COLLECTION:'products',
    FOODCATEGORY_COLLECTION:'foodCategories',
    SPECIAL_PRODUCTS_COLLECTION:'specialProducts',
    USER_COLLECTIONS:'accounts',
    CART_COLLECTION:'cart',
    ORDER_COLLECTION:'orders',
    ADMIN_COLLECTION:'admins',
    BANNER_COLLECTION:'banners',
    MESSAGE_COLLECTION:'messages',
    ADMIN_ANSWERS_COLLECTION:'answeredMessages',
    FAQS_COLLECTION:'faqs',
    ORDER_TRACKING_COLLECTION:'orderTracking'
}